### ISSUE TITLE
Permission based export [Feature]

### ISSUE THREAD

**Issue by NilsBaumgartner1994** [maltejur/directus-extension-generate-types#4]
First of all, thank you for your nice project ! That is something we need !

An idea would be, to export these Types for the specific permission for a role. Like with a role "User" you have only the types you are allowed to use and see.

**Comment by maltejur** [comment]
Interesting. So do you mean that you have a dropdown where you can select the role you want the types for? Or that it just gives you the types you have access to?

**Comment by NilsBaumgartner1994** [comment]
Well, when i am developing a user frontend app, i dont need all types, only those which the user can see/edit.

In a first step it would be nice to have a small dropdown to select the role.

**Comment by maltejur** [comment]
> Well, when i am developing a user frontend app

I am just trying to understand the usecase here, all users who use the directus app should be able to see the Typescript types, but only for the collections they have access to? So all users interact with the directus app via the Typescript API? I would expect that the only people who use the typescript types are the admins/developers of the directus app, but that doesn't seem to be the case for you. Since most people would probably not use that feature if I understand it correctly, could you try to explain a bit further why every user needs their own types in your case?

On another note, it would be very nice to have the whole module only shown to admins/people with a certain role. But that is currently not achievable with the directus extension API, see https://github.com/directus/directus/discussions/3211.

**Comment by NilsBaumgartner1994** [comment]
That is correct. Imagine that we hire or have someone in the team, which develops the frontend-app but does not need to know every field which exists in a collection. It's for the developer easier to focus only on the allowed fields.

In our scenario I have a small internship, where students should make a small app. They don't need to know all aspects of a collection.

**Comment by NilsBaumgartner1994** [comment]
OK that is already nice :-) So my students can fetch the types themself. Still it would be nice not necessarily to switch/create users for that purpose.

**Comment by NilsBaumgartner1994** [comment]
Is it somehow possible to access the collection name?

`directus.items(<INSERT HERE COLLECTION NAME?>)`

I just want to hardcode it in :-/

**Comment by maltejur** [comment]
> Is it somehow possible to access the collection name?
> directus.items(<INSERT HERE COLLECTION NAME?>)
> I just want to hardcode it in :-/

Can you explain a bit more what you mean, I don't really understand?
